// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Coffee wending

#ifndef _COFFEE_WENDING_UI_H
#define _COFFEE_WENDING_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Main
void ui_Main_screen_init(void);
extern lv_obj_t *ui_Main;
extern lv_obj_t *ui_main;
void ui_event_Button1( lv_event_t * e);
extern lv_obj_t *ui_Button1;
void ui_event_Button2( lv_event_t * e);
extern lv_obj_t *ui_Button2;
void ui_event_Button3( lv_event_t * e);
extern lv_obj_t *ui_Button3;
void ui_event_Button4( lv_event_t * e);
extern lv_obj_t *ui_Button4;
extern lv_obj_t *ui_Image8;
extern lv_obj_t *ui_Label2;
// SCREEN: ui_Payment
void ui_Payment_screen_init(void);
void ui_event_Payment( lv_event_t * e);
extern lv_obj_t *ui_Payment;
extern lv_obj_t *ui_Image2;
extern lv_obj_t *ui_Panel_QR;
void ui_event_Image3( lv_event_t * e);
extern lv_obj_t *ui_Image3;
extern lv_obj_t *ui_Image4;
extern lv_obj_t *ui_Label_Item;
extern lv_obj_t *ui_Label_Price;
extern lv_obj_t *ui_Image5;
extern lv_obj_t *ui_Label3;
// SCREEN: ui_Preparation
void ui_Preparation_screen_init(void);
void ui_event_Preparation( lv_event_t * e);
extern lv_obj_t *ui_Preparation;
extern lv_obj_t *ui_Image7;
extern lv_obj_t *ui_img_coffee;
extern lv_obj_t *ui_Image_mask;
extern lv_obj_t *ui_Img_glass;
extern lv_obj_t *ui_Label_Status;
extern lv_obj_t *ui_Image6;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_images_main_png);   // assets/images/main.png
LV_IMG_DECLARE( ui_img_images_logo_png);   // assets/images/logo.png
LV_IMG_DECLARE( ui_img_images_bg_png);   // assets/images/bg.png
LV_IMG_DECLARE( ui_img_images_button_back_png);   // assets/images/button_back.png
LV_IMG_DECLARE( ui_img_images_icon_card_png);   // assets/images/icon_card.png
LV_IMG_DECLARE( ui_img_images_coffee_png);   // assets/images/coffee.png
LV_IMG_DECLARE( ui_img_images_mask_png);   // assets/images/mask.png
LV_IMG_DECLARE( ui_img_images_empty_glass_png);   // assets/images/empty_glass.png


LV_FONT_DECLARE( ui_font_in25);
LV_FONT_DECLARE( ui_font_in30);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
