// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Coffee wending

#include "ui.h"

void button_espresso(lv_event_t * e)
{
	// Your code here
}

void button_americano(lv_event_t * e)
{
	// Your code here
}

void button_latte(lv_event_t * e)
{
	// Your code here
}

void button_irish(lv_event_t * e)
{
	// Your code here
}

void Payment_screen_loaded(lv_event_t * e)
{
	// Your code here
}

void Prep_screen_loaded(lv_event_t * e)
{
	// Your code here
}
