// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Coffee wending

#include "ui.h"

void button_espresso(lv_event_t * e) {
    lv_label_set_text(ui_Label_Item, "Espresso");
    lv_label_set_text(ui_Label_Price, "2.99");
}

void button_americano(lv_event_t * e) {
    lv_label_set_text(ui_Label_Item, "Americano");
    lv_label_set_text(ui_Label_Price, "3.99");
}

void button_latte(lv_event_t * e) {
    lv_label_set_text(ui_Label_Item, "Latte");
    lv_label_set_text(ui_Label_Price, "4.50");
}

void button_irish(lv_event_t * e) {
    lv_label_set_text(ui_Label_Item, "Irish Coffee");
    lv_label_set_text(ui_Label_Price, "5.99");
}

// Function to generate a QR code
lv_obj_t * generate_qr_code(const char * text) {
    lv_obj_t * qr = lv_qrcode_create(lv_scr_act(), 230, lv_color_hex3(0x000), lv_color_hex3(0xFFF));
    lv_qrcode_update(qr, text, strlen(text));
    return qr;
}

static lv_obj_t * qr_code;

void Payment_screen_loaded(lv_event_t * e) {
    // Generate and display QR code
    qr_code = generate_qr_code("www.youtube.com/nishad2m8/");
    lv_obj_set_parent(qr_code, ui_Panel_QR);
    lv_obj_center(qr_code); // Align the QR code to the center of ui_Panel_QR
}

// Callback function to update the status label
void update_status_label(lv_timer_t * timer) {
    lv_label_set_text(ui_Label_Status, "Ready, please take your drink");
}

void Prep_screen_loaded(lv_event_t * e) {
    // Set the status label to "Preparing your drink"
    lv_label_set_text(ui_Label_Status, "Preparing your drink");

    // Create an animation to move the coffee image from y position 135 to 40 over 5 seconds
    lv_anim_t a;
    lv_anim_init(&a);
    lv_anim_set_var(&a, ui_img_coffee);
    lv_anim_set_values(&a, 135, 40);
    lv_anim_set_time(&a, 7000); // 7 seconds
    lv_anim_set_exec_cb(&a, (lv_anim_exec_xcb_t)lv_obj_set_y);
    lv_anim_start(&a);

    // Create a timer to update the status label after 7 seconds
    lv_timer_create(update_status_label, 7000, NULL);
}