// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Coffee wending

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void button_espresso(lv_event_t * e);
void button_americano(lv_event_t * e);
void button_latte(lv_event_t * e);
void button_irish(lv_event_t * e);
void Payment_screen_loaded(lv_event_t * e);
void Prep_screen_loaded(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
