// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Coffee wending

#include "../ui.h"

void ui_Payment_screen_init(void)
{
ui_Payment = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Payment, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image2 = lv_img_create(ui_Payment);
lv_img_set_src(ui_Image2, &ui_img_images_bg_png);
lv_obj_set_width( ui_Image2, LV_SIZE_CONTENT);  /// 480
lv_obj_set_height( ui_Image2, LV_SIZE_CONTENT);   /// 480
lv_obj_set_align( ui_Image2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel_QR = lv_obj_create(ui_Payment);
lv_obj_set_width( ui_Panel_QR, 250);
lv_obj_set_height( ui_Panel_QR, 250);
lv_obj_set_x( ui_Panel_QR, 0 );
lv_obj_set_y( ui_Panel_QR, -28 );
lv_obj_set_align( ui_Panel_QR, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel_QR, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel_QR, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel_QR, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image3 = lv_img_create(ui_Payment);
lv_img_set_src(ui_Image3, &ui_img_images_button_back_png);
lv_obj_set_width( ui_Image3, LV_SIZE_CONTENT);  /// 133
lv_obj_set_height( ui_Image3, LV_SIZE_CONTENT);   /// 46
lv_obj_set_x( ui_Image3, -142 );
lv_obj_set_y( ui_Image3, 194 );
lv_obj_set_align( ui_Image3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image4 = lv_img_create(ui_Payment);
lv_img_set_src(ui_Image4, &ui_img_images_icon_card_png);
lv_obj_set_width( ui_Image4, LV_SIZE_CONTENT);  /// 102
lv_obj_set_height( ui_Image4, LV_SIZE_CONTENT);   /// 70
lv_obj_set_x( ui_Image4, 165 );
lv_obj_set_y( ui_Image4, 190 );
lv_obj_set_align( ui_Image4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image4, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label_Item = lv_label_create(ui_Payment);
lv_obj_set_width( ui_Label_Item, 156);
lv_obj_set_height( ui_Label_Item, 33);
lv_obj_set_x( ui_Label_Item, -42 );
lv_obj_set_y( ui_Label_Item, 120 );
lv_obj_set_align( ui_Label_Item, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_Label_Item,LV_LABEL_LONG_DOT);
lv_label_set_text(ui_Label_Item,"Irish Coffee");
lv_obj_set_style_text_align(ui_Label_Item, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Item, &ui_font_in30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_Price = lv_label_create(ui_Payment);
lv_obj_set_width( ui_Label_Price, 104);
lv_obj_set_height( ui_Label_Price, 33);
lv_obj_set_x( ui_Label_Price, 69 );
lv_obj_set_y( ui_Label_Price, 120 );
lv_obj_set_align( ui_Label_Price, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_Price,"00.00");
lv_obj_set_style_text_align(ui_Label_Price, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Price, &ui_font_in30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image5 = lv_img_create(ui_Payment);
lv_img_set_src(ui_Image5, &ui_img_images_logo_png);
lv_obj_set_width( ui_Image5, LV_SIZE_CONTENT);  /// 48
lv_obj_set_height( ui_Image5, LV_SIZE_CONTENT);   /// 48
lv_obj_set_x( ui_Image5, 34 );
lv_obj_set_y( ui_Image5, 7 );
lv_obj_add_flag( ui_Image5, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label3 = lv_label_create(ui_Payment);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, 0 );
lv_obj_set_y( ui_Label3, -174 );
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"Payment");
lv_obj_set_style_text_font(ui_Label3, &ui_font_in25, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Image3, ui_event_Image3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Payment, ui_event_Payment, LV_EVENT_ALL, NULL);

}
