// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Coffee wending

#include "../ui.h"

void ui_Main_screen_init(void)
{
ui_Main = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Main, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Main, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Main, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button1 = lv_btn_create(ui_Main);
lv_obj_set_width( ui_Button1, 186);
lv_obj_set_height( ui_Button1, 162);
lv_obj_set_x( ui_Button1, -110 );
lv_obj_set_y( ui_Button1, -90 );
lv_obj_set_align( ui_Button1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Button1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image11 = lv_img_create(ui_Button1);
lv_img_set_src(ui_Image11, &ui_img_images_img_price_png);
lv_obj_set_width( ui_Image11, LV_SIZE_CONTENT);  /// 89
lv_obj_set_height( ui_Image11, LV_SIZE_CONTENT);   /// 43
lv_obj_set_x( ui_Image11, 43 );
lv_obj_set_y( ui_Image11, 16 );
lv_obj_set_align( ui_Image11, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image11, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image11, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image2 = lv_img_create(ui_Button1);
lv_img_set_src(ui_Image2, &ui_img_images_img_espresso_png);
lv_obj_set_width( ui_Image2, LV_SIZE_CONTENT);  /// 108
lv_obj_set_height( ui_Image2, LV_SIZE_CONTENT);   /// 132
lv_obj_set_x( ui_Image2, -32 );
lv_obj_set_y( ui_Image2, -7 );
lv_obj_set_align( ui_Image2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label1 = lv_label_create(ui_Button1);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, -31 );
lv_obj_set_y( ui_Label1, 66 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"Espresso");
lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xCFCFCF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label1, &ui_font_in20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label4 = lv_label_create(ui_Button1);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4, 48 );
lv_obj_set_y( ui_Label4, 15 );
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"2.99");
lv_obj_set_style_text_font(ui_Label4, &ui_font_in30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button2 = lv_btn_create(ui_Main);
lv_obj_set_width( ui_Button2, 186);
lv_obj_set_height( ui_Button2, 162);
lv_obj_set_x( ui_Button2, 126 );
lv_obj_set_y( ui_Button2, -91 );
lv_obj_set_align( ui_Button2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Button2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Button2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image13 = lv_img_create(ui_Button2);
lv_img_set_src(ui_Image13, &ui_img_images_img_price_png);
lv_obj_set_width( ui_Image13, LV_SIZE_CONTENT);  /// 89
lv_obj_set_height( ui_Image13, LV_SIZE_CONTENT);   /// 43
lv_obj_set_x( ui_Image13, 43 );
lv_obj_set_y( ui_Image13, 16 );
lv_obj_set_align( ui_Image13, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image13, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image13, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image7 = lv_img_create(ui_Button2);
lv_img_set_src(ui_Image7, &ui_img_images_img_espresso_png);
lv_obj_set_width( ui_Image7, LV_SIZE_CONTENT);  /// 108
lv_obj_set_height( ui_Image7, LV_SIZE_CONTENT);   /// 132
lv_obj_set_x( ui_Image7, -32 );
lv_obj_set_y( ui_Image7, -7 );
lv_obj_set_align( ui_Image7, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image7, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label6 = lv_label_create(ui_Button2);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label6, 48 );
lv_obj_set_y( ui_Label6, 15 );
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"3.99");
lv_obj_set_style_text_font(ui_Label6, &ui_font_in30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label7 = lv_label_create(ui_Button2);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label7, -29 );
lv_obj_set_y( ui_Label7, 68 );
lv_obj_set_align( ui_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label7,"Americano");
lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xCFCFCF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label7, &ui_font_in20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button3 = lv_btn_create(ui_Main);
lv_obj_set_width( ui_Button3, 186);
lv_obj_set_height( ui_Button3, 211);
lv_obj_set_x( ui_Button3, -108 );
lv_obj_set_y( ui_Button3, 111 );
lv_obj_set_align( ui_Button3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Button3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Button3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image14 = lv_img_create(ui_Button3);
lv_img_set_src(ui_Image14, &ui_img_images_img_price_png);
lv_obj_set_width( ui_Image14, LV_SIZE_CONTENT);  /// 89
lv_obj_set_height( ui_Image14, LV_SIZE_CONTENT);   /// 43
lv_obj_set_x( ui_Image14, 37 );
lv_obj_set_y( ui_Image14, 43 );
lv_obj_set_align( ui_Image14, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image14, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image14, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image9 = lv_img_create(ui_Button3);
lv_img_set_src(ui_Image9, &ui_img_images_img_latte_png);
lv_obj_set_width( ui_Image9, LV_SIZE_CONTENT);  /// 108
lv_obj_set_height( ui_Image9, LV_SIZE_CONTENT);   /// 194
lv_obj_set_x( ui_Image9, -32 );
lv_obj_set_y( ui_Image9, -7 );
lv_obj_set_align( ui_Image9, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image9, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label8 = lv_label_create(ui_Button3);
lv_obj_set_width( ui_Label8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label8, -31 );
lv_obj_set_y( ui_Label8, 95 );
lv_obj_set_align( ui_Label8, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label8,"Latte");
lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xCFCFCF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label8, &ui_font_in20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label10 = lv_label_create(ui_Button3);
lv_obj_set_width( ui_Label10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label10, 46 );
lv_obj_set_y( ui_Label10, 43 );
lv_obj_set_align( ui_Label10, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label10,"4.50");
lv_obj_set_style_text_font(ui_Label10, &ui_font_in30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button4 = lv_btn_create(ui_Main);
lv_obj_set_width( ui_Button4, 186);
lv_obj_set_height( ui_Button4, 211);
lv_obj_set_x( ui_Button4, 125 );
lv_obj_set_y( ui_Button4, 110 );
lv_obj_set_align( ui_Button4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Button4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Button4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image15 = lv_img_create(ui_Button4);
lv_img_set_src(ui_Image15, &ui_img_images_img_price_png);
lv_obj_set_width( ui_Image15, LV_SIZE_CONTENT);  /// 89
lv_obj_set_height( ui_Image15, LV_SIZE_CONTENT);   /// 43
lv_obj_set_x( ui_Image15, 37 );
lv_obj_set_y( ui_Image15, 43 );
lv_obj_set_align( ui_Image15, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image15, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image15, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image10 = lv_img_create(ui_Button4);
lv_img_set_src(ui_Image10, &ui_img_images_img_irish_coffee_png);
lv_obj_set_width( ui_Image10, LV_SIZE_CONTENT);  /// 102
lv_obj_set_height( ui_Image10, LV_SIZE_CONTENT);   /// 184
lv_obj_set_x( ui_Image10, -32 );
lv_obj_set_y( ui_Image10, -7 );
lv_obj_set_align( ui_Image10, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image10, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image10, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label9 = lv_label_create(ui_Button4);
lv_obj_set_width( ui_Label9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label9, -31 );
lv_obj_set_y( ui_Label9, 95 );
lv_obj_set_align( ui_Label9, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label9,"Irish Coffee");
lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0xCFCFCF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label9, &ui_font_in20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label11 = lv_label_create(ui_Button4);
lv_obj_set_width( ui_Label11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label11, 46 );
lv_obj_set_y( ui_Label11, 43 );
lv_obj_set_align( ui_Label11, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label11,"5.99");
lv_obj_set_style_text_font(ui_Label11, &ui_font_in30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image8 = lv_img_create(ui_Main);
lv_img_set_src(ui_Image8, &ui_img_images_logo_png);
lv_obj_set_width( ui_Image8, LV_SIZE_CONTENT);  /// 48
lv_obj_set_height( ui_Image8, LV_SIZE_CONTENT);   /// 48
lv_obj_set_x( ui_Image8, 34 );
lv_obj_set_y( ui_Image8, 7 );
lv_obj_add_flag( ui_Image8, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label2 = lv_label_create(ui_Main);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, 0 );
lv_obj_set_y( ui_Label2, -174 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"Slect your drink");
lv_obj_set_style_text_font(ui_Label2, &ui_font_in25, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image1 = lv_img_create(ui_Main);
lv_img_set_src(ui_Image1, &ui_img_images_img_devider_png);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 457
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 26
lv_obj_set_x( ui_Image1, -4 );
lv_obj_set_y( ui_Image1, 38 );
lv_obj_set_align( ui_Image1, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);

}
